### ISSUE TITLE
Chapter 10 examples do not run

### ISSUE THREAD

**Issue by csmu-cenr** [PacktPublishing/React-and-React-Native#5]
Please explain how we run the examples in Chapter 10.

**Comment by csmu-cenr** [comment]
rendering-to-strings webpack.config,js is wrong.

rendering-to-strings admin$ webpack-dev-server --hot
Project is running at http://localhost:8080/
webpack output is served from /
Hash: a84ef46c111b6fb1c551
Version: webpack 2.6.1
Time: 928ms
         Asset    Size  Chunks                    Chunk Names
main-bundle.js  341 kB       0  [emitted]  [big]  main
chunk    {0} main-bundle.js (main) 303 kB [entry] [rendered]
   [36] (webpack)-dev-server/client?http://localhost:8080 5.68 kB {0} [built]
   [37] /source/React-and-React-Native/~/webpack/hot/dev-server.js 1.57 kB {0} [built]
   [38] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
   [39] (webpack)-dev-server/client/socket.js 897 bytes {0} [built]
   [40] (webpack)-dev-server/~/ansi-html/index.js 4.26 kB {0} [built]
   [41] (webpack)-dev-server/~/ansi-regex/index.js 135 bytes {0} [built]
   [48] (webpack)-dev-server/~/sockjs-client/lib/entry.js 244 bytes {0} [built]
   [74] (webpack)-dev-server/~/strip-ansi/index.js 161 bytes {0} [built]
   [77] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [78] (webpack)/~/punycode/punycode.js 14.7 kB {0} [built]
   [81] (webpack)/~/querystring-es3/index.js 127 bytes {0} [built]
   [82] (webpack)/~/url/url.js 23.3 kB {0} [built]
   [84] /source/React-and-React-Native/~/webpack/hot/emitter.js 77 bytes {0} [built]
   [85] /source/React-and-React-Native/~/webpack/hot/log-apply-result.js 1.02 kB {0} [built]
   [86] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./main.js 52 bytes {0} [built]
     + 72 hidden modules

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./main.js
Module not found: Error: Can't resolve './main.js' in '/source/React-and-React-Native/Chapter10/rendering-to-strings'
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./main.js
webpack: Failed to compile.

**Comment by csmu-cenr** [comment]
Changing webpack.config.js to use server.js as the entry point results in.

rendering-to-strings admin$ webpack-dev-server --hot
Project is running at http://localhost:8080/
webpack output is served from /
Hash: a84ef46c111b6fb1c551
Version: webpack 2.6.1
Time: 921ms
         Asset    Size  Chunks                    Chunk Names
main-bundle.js  341 kB       0  [emitted]  [big]  main
chunk    {0} main-bundle.js (main) 303 kB [entry] [rendered]
   [36] (webpack)-dev-server/client?http://localhost:8080 5.68 kB {0} [built]
   [37] /source/React-and-React-Native/~/webpack/hot/dev-server.js 1.57 kB {0} [built]
   [38] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
   [39] (webpack)-dev-server/client/socket.js 897 bytes {0} [built]
   [40] (webpack)-dev-server/~/ansi-html/index.js 4.26 kB {0} [built]
   [41] (webpack)-dev-server/~/ansi-regex/index.js 135 bytes {0} [built]
   [48] (webpack)-dev-server/~/sockjs-client/lib/entry.js 244 bytes {0} [built]
   [74] (webpack)-dev-server/~/strip-ansi/index.js 161 bytes {0} [built]
   [77] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [78] (webpack)/~/punycode/punycode.js 14.7 kB {0} [built]
   [81] (webpack)/~/querystring-es3/index.js 127 bytes {0} [built]
   [82] (webpack)/~/url/url.js 23.3 kB {0} [built]
   [84] /source/React-and-React-Native/~/webpack/hot/emitter.js 77 bytes {0} [built]
   [85] /source/React-and-React-Native/~/webpack/hot/log-apply-result.js 1.02 kB {0} [built]
   [86] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./server.js 52 bytes {0} [built]
     + 72 hidden modules

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./server.js
Module not found: Error: Can't resolve 'react-hot' in '/source/React-and-React-Native/Chapter10/rendering-to-strings'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'react-hot-loader' instead of 'react-hot',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./server.js
webpack: Failed to compile.

**Comment by adamboduch** [comment]
Hi @csmu-cenr.

Sorry for the delayed response. I've added a bit of clarifying info to the README regarding examples that have a `server.js` file. In short, some of the examples render React components on the server, so we need to tell Node have to run these. In the examples you've mentioned, I had mistakenly left unused `webpack.config.js` files there. These have been removed.

So to get these examples running, install the Babel command line if you haven't already:
```bash
npm install babel babel-cli -g
```

Then use Babel to run `server.js` directly:
```bash
babel-node server.js
```

Let me know how this goes. See 6487e79c2684c10fd3e291b555546919c3eb49d4.

**Comment by csmu-cenr** [comment]
Thanks Adam

backend-routing and rendering-to-strings now works.

fetching-data fails with

csmu-macbook-pro-2:fetching-data admin$ babel-node server.js
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
/source/React-and-React-Native/node_modules/webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'default'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           default: ...
         }
       })
     ]
    at webpack (/source/React-and-React-Native/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/source/React-and-React-Native/Chapter10/fetching-data/server.js:71:30)
    at Module._compile (module.js:571:32)
    at loader (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/babel-cli/lib/_babel-node.js:154:22)

frontend-reconciliation

babel-node server.js works

and webpack-dev-server --hot shows a directory list.

**Comment by adamboduch** [comment]
@csmu-cenr, thanks for pointing this out. Fixed in 25123755f18d73b4d0fb8b1378d20688a686ef85
