### ISSUE TITLE
Please explain how to run the examples in Chapter 11

### ISSUE THREAD

**Issue by csmu-cenr** [PacktPublishing/React-and-React-Native#6]
I start the example then a short time later it crashes.

 webpack-dev-server --hot
Project is running at http://localhost:8080/
webpack output is served from /
/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:35
			throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
			^

Error: Module '/source/React-and-React-Native/node_modules/url/url.js' is not a loader (must have normal or pitch function)
    at loadLoader (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:35:10)
    at iteratePitchingLoaders (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/lib/NormalModule.js:268:15)
    at Compilation.buildModule (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/lib/Compilation.js:146:10)
    at factoryCallback (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/lib/Compilation.js:329:11)
    at factory (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/lib/NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (/Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/lib/NormalModuleFactory.js:99:14)
    at /Users/admin/.nvm/versions/node/v7.8.0/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:204:11

**Comment by adamboduch** [comment]
Hi @csmu-cenr,

I've fixed the invalid `webpack.config.js` that's causing this issue.

See 187b85ffe454ec4e02bec8f663ceaa9e53dd55f1.

**Comment by csmu-cenr** [comment]
Thanks Adam ... it now works after running react-bootstrap admin$ webpack-dev-server --hot

Cheers

Keith
